import { Component, OnInit } from '@angular/core';
import { Column } from '../../../../../interfaces/filter/column';
import { BaseService } from '../../../../../shared/services/base.service';

@Component({
  selector: 'app-incidecias-resultados',
  templateUrl: './incidecias-resultados.component.html',
  styleUrls: ['./incidecias-resultados.component.css']
})
export class IncideciasResultadosComponent extends BaseService implements OnInit {
  columnsAvance: Array<Column> = [];
  muestreos: Array<any> = [];
  muestreosSeleccionados: Array<any> = [];

  constructor() { super(); }

  ngOnInit(): void {
    this.definirColumnas();
  }

  definirColumnas() {
    let nombresColumnas: Array<Column> = [
      {
        name: 'numentrega',
        label: 'N° ENTREGA',
        order: 1,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color:'#C9C9C9',
      },
      {
        name: 'claveUnica',
        label: 'CLAVE ÚNICA',
        order: 2,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084'
      },
      {
        name: 'claveSitio',
        label: 'CLAVE SITIO',
        order: 3,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',
      },
      {
        name: 'claveMonitoreo',
        label: 'CLAVE MONITOREO',
        order: 4,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'number',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',
      },
      {
        name: 'nombreParametro',
        label: 'NOMBRE',
        order: 5,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',
      },
      {
        name: 'claveParametro',
        label: 'CLAVE PARÁMETRO',
        order: 6,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',
      },
      {
        name: 'laboratorio',
        label: 'LABORATORIO',
        order: 7,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',
      },
      {
        name: 'tipoCuerpoAgua',
        label: 'TIPO CUERPO DE AGUA',
        order: 8,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',
      },
      {
        name: 'tipoCuerpoAguaOriginal',
        label: 'TIPO CUERPO DE AGUA ORIGINAL',
        order: 9,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',
      },
      {
        name: 'resultado',
        label: 'RESULTADO',
        order: 10,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',
      },
      {
        name: 'esCorrecto',
        label: 'ES CORRECTO EL RESULTADO POR REGLAS DE VALIDACIÓN',
        order: 11,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color:'#8EA9DB',
      },
      {
        name: 'observacionReglasValidacion',
        label: 'OBSERVACIÓN REGLAS DE VALIDACIÓN',
        order: 12,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#8EA9DB',
      },
      {
        name: 'aceptaRechazo',
        label: 'SE ACEPTA RECHAZO SI/NO',
        order: 13,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color:'#FF66FF',
      },
      {
        name: 'resultadoReplica',
        label: 'RESULTADO RÉPLICA',
        order: 14,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',
      },
      {
        name: 'mismoResultado',
        label: 'ES EL MISMO RESULTADO',
        order: 15,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',
      },
      {
        name: 'observacionLaboratorio',
        label: 'OBSERVACIÓN LABORATORIO',
        order: 16,
        selectAll: true,
        filtered: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',
      },
      {
        name: 'fechaReplicaLaboratorio',
        label: 'FECHA DE RÉPLICA LABORATORIO',
        order: 17,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',
      },
      {
        name: 'observacionSrenameca',
        label: 'OBSERVACIÓN SRENAMECA',
        order: 18,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color:'#00B0F0',
      },
      {
        name: 'esCorrectoDato',
        label: '¿EL DATO ES CORRECTO?',
        order: 19,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color:'#00B0F0',
      },
      {
        name: 'fechaObservacionSrenameca',
        label: 'FECHA DE OBSERVACIÓN SRENAMECA',
        order: 20,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#00B0F0',
      },
      {
        name: 'observacionReglasReplica',
        label: 'OBSERVACIONES REGLAS RÉPLICA',
        order: 21,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color:'#F8CBAD',
      },
      {
      name: 'aprobacíonResultado',
      label: 'SE APRUEBA EL RESULTADO DESPUES DE LA RÉPLICA',
      order: 22,
      selectAll: true,
      filtered: false,
      desc: false,
      asc: false,
      data: [],
      filteredData: [],
      dataType: 'date',
      specialFilter: '',
      secondSpecialFilter: '',
        selectedData: '',
        color:'#9966FF',
      },
      {
        name: 'fechaEstatusFinal',
        label: 'FECHA DE ESTATUS FINAL',
        order: 23,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color:'#A9D08E',
      },
      {
        name: 'usuarioReviso',
        label: 'USUARIO QUE REVISÓ',
        order: 24,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#A9D08E',
      },
      {
        name: 'estatusResultado',
        label: 'ESTATUS DEL RESULTADO',
        order: 25,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color:'#FFFF00',
      },
      {
        name: 'arcivo',
        label: 'NOMBRE ARCHIVO DE EVIDENCIAS',
        order: 26,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color:'#FF66FF',
      },
      {
        name: 'evidenciasReplica',
        label: 'EVIDENCIAS RÉPLICA',
        order: 27,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',
      }
    ];

    let avanceEstatusColumnas: Array<Column> = [
      {
        name: 'claveUnica',
        label: 'CLAVE ÚNICA',
        order: 1,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F4B084',
      },
      {
        name: '',
        label: '1.RECHAZADO POR REGLAS DE VALIDACIÓN',
        order: 2,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#8EA9DB'
      },
      {
        name: '',
        label: '2.RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO EXTERNO',
        order: 3,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',
      },
      {
        name: '',
        label: '3.RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO EXTERNO - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA',
        order: 4,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'number',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',
      },
      {
        name: '',
        label: '4.RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA',
        order: 5,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#00B0F0',
      },
      {
        name: '',
        label: '5.RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA - CARGA VALIDACIÓN SRENAMECA',
        order: 6,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#00B0F0',
      },
      {
        name: '',
        label: '3.1 ENVIADO A REGISTRO ORIGINAL ACUMULACIÓN DE RESULTADOS',
        order: 7,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#99FFCC',
      },
      {
        name: '',
        label: '3.2 ENVIADO A REGISTRO ORIGINAL ACUMULACIÓN DE RESULTADOS -INICIAL DE REGLAS',
        order: 8,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#99FFCC',
      },
      {
        name: '',
        label: '3.3ENVIADO A REGISTRO ORIGINAL ACUMULACIÓN DE RESULTADOS -INICIAL DE REGLAS - MÓDULO DE REGLAS',
        order: 9,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#99FFCC',
      },
      {
        name: '',
        label: '3.4 ENVIADO A REGISTRO ORIGINAL ACUMULACIÓN DE RESULTADOS - INICIAL DE REGLAS - MÓDULO DE REGLAS - RESUMEN REGLAS',
        order: 10,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#99FFCC',
      },
      {
        name: '',
        label: '6.1 RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA - CARGA VALIDACIÓN SRENAMECA - ENVIADO A RESUMEN DE RESULTADOS (2.4)',
        order: 11,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#AA7EEA',
      },
      {
        name: '',
        label: '6.1.1 RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA - CARGA VALIDACIÓN SRENAMECA - ENVIADO A RESUMEN DE RESULTADOS (2.4) - ENVIADO A LIBERACIÓN DE RESULTADOS',
        order: 12,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FFC000',
      },
      {
        name: '',
        label: '6.1.2 RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA - CARGA VALIDACIÓN SRENAMECA - ENVIADO A RESUMEN DE RESULTADOS (2.4)- ENVIADO A PENALIZACIÓN',
        order: 13,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FFC000',
      }     
    ];

    this.columns = nombresColumnas;
    this.columnsAvance = avanceEstatusColumnas;
    this.setHeadersList(this.columns);
  }

  cargarArchivo(event: any) { }
  enviarCorreo() { }
  onFilterIconClick(column: Column) { }
  sort(column: string, type: string) { }
  onDeleteFilterClick(columName: string) { }
  filtrar(columna: Column, isFiltroEspecial: boolean) { }
  onSelectClick(muestreo: any) { }

  

}
