import { Component, OnInit } from '@angular/core';
import { Column } from '../../../../../interfaces/filter/column';
import { ReplicasResultadosReglaVal } from '../../../../../interfaces/ReplicasResultadosReglaVal.interface';
import { estatusResultado } from '../../../../../shared/enums/estatusResultado';
import { BaseService } from '../../../../../shared/services/base.service';
import { IncidenciasResultadosService } from '../../services/incidencias-resultados.service';

@Component({
  selector: 'app-incidecias-resultados',
  templateUrl: './incidecias-resultados.component.html',
  styleUrls: ['./incidecias-resultados.component.css']
})
export class IncideciasResultadosComponent extends BaseService implements OnInit {
  columnsAvance: Array<Column> = [];

  replicasResultados: Array<ReplicasResultadosReglaVal> = [];
  resultadosFiltrados: Array<ReplicasResultadosReglaVal> = [];
  constructor(private IncidenciasResultadoService: IncidenciasResultadosService) { super(); }

  ngOnInit(): void {
    this.definirColumnas();
    this.consultarReplicas();
  }

  definirColumnas() {
    let nombresColumnas: Array<Column> = [
      {
        name: 'numentrega',
        label: 'N° ENTREGA',
        order: 1,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#C9C9C9',        
        width: 50.68,
       

      },
      {
        name: 'claveUnica',
        label: 'CLAVE ÚNICA',
        order: 2,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',        
        width:61.96,
        
      },
      {
        name: 'claveSitio',
        label: 'CLAVE SITIO',
        order: 3,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',        
        width:66.95,
      },
      {
        name: 'claveMonitoreo',
        label: 'CLAVE MONITOREO',
        order: 4,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'number',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',        
        width:63.53,
      },
      {
        name: 'nombreParametro',
        label: 'NOMBRE',
        order: 5,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',        
        width:244.76,
      },
      {
        name: 'claveParametro',
        label: 'CLAVE PARÁMETRO',
        order: 6,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',        
        width:65.79,
      },
      {
        name: 'laboratorio',
        label: 'LABORATORIO',
        order: 7,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',        
        width:75.79,
      },
      {
        name: 'tipoCuerpoAgua',
        label: 'TIPO CUERPO DE AGUA',
        order: 8,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',        
        width:104.93,
      },
      {
        name: 'tipoCuerpoAguaOriginal',
        label: 'TIPO CUERPO DE AGUA ORIGINAL',
        order: 9,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',        
        width:104.94,
      },
      {
        name: 'resultado',
        label: 'RESULTADO',
        order: 10,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F5B084',        
        width:85.96,
      },
      {
        name: 'esCorrecto',
        label: 'ES CORRECTO EL RESULTADO POR REGLAS DE VALIDACIÓN',
        order: 11,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#8EA9DB',        
        width:127.93,
      },
      {
        name: 'observacionReglasValidacion',
        label: 'OBSERVACIÓN REGLAS DE VALIDACIÓN',
        order: 12,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#8EA9DB',        
        width:151.9,
      },
      {
        name: 'aceptaRechazo',
        label: 'SE ACEPTA RECHAZO SI/NO',
        order: 13,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',        
        width:51.24,
      },
      {
        name: 'resultadoReplica',
        label: 'RESULTADO RÉPLICA',
        order: 14,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',        
        width: 62.76,
      },
      {
        name: 'mismoResultado',
        label: 'ES EL MISMO RESULTADO',
        order: 15,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',        
        width: 62.76,
      },
      {
        name: 'observacionLaboratorio',
        label: 'OBSERVACIÓN LABORATORIO',
        order: 16,
        selectAll: true,
        filtered: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',        
        width: 75.81,
      },
      {
        name: 'fechaReplicaLaboratorio',
        label: 'FECHA DE RÉPLICA LABORATORIO',
        order: 17,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',        
        width: 75.79,
      },
      {
        name: 'observacionSrenameca',
        label: 'OBSERVACIÓN SRENAMECA',
        order: 18,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#00B0F0',        
        width: 75.81,
      },
      {
        name: 'esCorrectoDato',
        label: '¿EL DATO ES CORRECTO?',
        order: 19,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#00B0F0',        
        width: 65.21,
      },
      {
        name: 'fechaObservacionSrenameca',
        label: 'FECHA DE OBSERVACIÓN SRENAMECA',
        order: 20,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#00B0F0',        
        width: 75.81,
      },
      {
        name: 'observacionReglasReplica',
        label: 'OBSERVACIONES REGLAS RÉPLICA',
        order: 21,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F8CBAD',        
        width: 211.8,
      },
      {
      name: 'aprobacíonResultado',
      label: 'SE APRUEBA EL RESULTADO DESPUES DE LA RÉPLICA',
      order: 22,
      selectAll: true,
      filtered: false,
      desc: false,
      asc: false,
      data: [],
      filteredData: [],
      dataType: 'date',
      specialFilter: '',
      secondSpecialFilter: '',
        selectedData: '',
        color: '#9966FF',        
        width: 225.89
      },
      {
        name: 'fechaEstatusFinal',
        label: 'FECHA DE ESTATUS FINAL',
        order: 23,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#A9D08E',        
        width: 87.93,
      },
      {
        name: 'usuarioReviso',
        label: 'USUARIO QUE REVISÓ',
        order: 24,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#A9D08E',        
        width: 89.93,
      },
      {
        name: 'estatusResultado',
        label: 'ESTATUS DEL RESULTADO',
        order: 25,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FFFF00',        
        width: 453.43
      },
      {
        name: 'arcivo',
        label: 'NOMBRE ARCHIVO DE EVIDENCIAS',
        order: 26,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',        
        width: 92.95,
      },
      {
        name: 'evidenciasReplica',
        label: 'EVIDENCIAS RÉPLICA',
        order: 27,
        selectAll: true,
        filtered: false,
        desc: false,
        asc: false,
        data: [],
        filteredData: [],
        dataType: 'date',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',        
        width: 98.94
      }
    ];

    let avanceEstatusColumnas: Array<Column> = [
      {
        name: 'claveUnica',
        label: 'CLAVE ÚNICA',
        order: 1,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#F4B084',        
        width: 168.8,
      },
      {
        name: '',
        label: '1.RECHAZADO POR REGLAS DE VALIDACIÓN',
        order: 2,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#8EA9DB',        
        width: 110.94,
      },
      {
        name: '',
        label: '2.RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO EXTERNO',
        order: 3,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',        
        width: 214.8,
      },
      {
        name: '',
        label: '3.RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO EXTERNO - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA',
        order: 4,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'number',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FF66FF',        
        width: 252.74,
      },
      {
        name: '',
        label: '4.RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA',
        order: 5,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#00B0F0',        
        width: 313.65
      },
      {
        name: '',
        label: '5.RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA - CARGA VALIDACIÓN SRENAMECA',
        order: 6,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#00B0F0',        
        width: 387.55,
      },
      {
        name: '',
        label: '3.1 ENVIADO A REGISTRO ORIGINAL ACUMULACIÓN DE RESULTADOS',
        order: 7,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#99FFCC',        
        width: 161.88,
      },
      {
        name: '',
        label: '3.2 ENVIADO A REGISTRO ORIGINAL ACUMULACIÓN DE RESULTADOS -INICIAL DE REGLAS',
        order: 8,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#99FFCC',        
        width: 188.84,
      },
      {
        name: '',
        label: '3.3ENVIADO A REGISTRO ORIGINAL ACUMULACIÓN DE RESULTADOS -INICIAL DE REGLAS - MÓDULO DE REGLAS',
        order: 9,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#99FFCC',        
        width: 214.8
      },
      {
        name: '',
        label: '3.4 ENVIADO A REGISTRO ORIGINAL ACUMULACIÓN DE RESULTADOS - INICIAL DE REGLAS - MÓDULO DE REGLAS - RESUMEN REGLAS',
        order: 10,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#99FFCC',        
        width: 184.84,
      },
      {
        name: '',
        label: '6.1 RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA - CARGA VALIDACIÓN SRENAMECA - ENVIADO A RESUMEN DE RESULTADOS (2.4)',
        order: 11,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#AA7EEA',        
        width: 363.59
      },
      {
        name: '',
        label: '6.1.1 RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA - CARGA VALIDACIÓN SRENAMECA - ENVIADO A RESUMEN DE RESULTADOS (2.4) - ENVIADO A LIBERACIÓN DE RESULTADOS',
        order: 12,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FFC000',        
        width: 404.53,
      },
      {
        name: '',
        label: '6.1.2 RECHAZADO POR REGLAS DE VALIDACIÓN - ENVIADO A LABORATORIO (CONALAB) - CARGA RÉPLICAS LAB EXTERNO Y ENVIADO A EBASECA - ENVIADO A SRENAMECA - CARGA VALIDACIÓN SRENAMECA - ENVIADO A RESUMEN DE RESULTADOS (2.4)- ENVIADO A PENALIZACIÓN',
        order: 13,
        selectAll: true,
        filtered: false,
        asc: false,
        desc: false,
        data: [],
        filteredData: [],
        dataType: 'string',
        specialFilter: '',
        secondSpecialFilter: '',
        selectedData: '',
        color: '#FFC000',        
        width: 420.69
       
      }     
    ];

    this.columns = nombresColumnas;
    this.columnsAvance = avanceEstatusColumnas;
    this.setHeadersList(this.columns);
  }

  consultarReplicas(
    page: number = this.page,
    pageSize: number = this.NoPage,
    filter: string = this.cadena
  ): void {
    this.IncidenciasResultadoService
      .getReplicasResultadosPaginados(
        estatusResultado.IncidenciasResultados,
        page,
        pageSize,
        filter,
        this.orderBy
      )
      .subscribe({
        next: (response: any) => {
          this.selectedPage = false;
          this.replicasResultados = response.data;
          console.log(response.data);
          this.page = response.totalRecords !== this.totalItems ? 1 : this.page;
          this.totalItems = response.totalRecords;
          this.getPreviousSelected(
            this.replicasResultados,
            this.resultadosFiltrados
          );
          this.selectedPage = this.anyUnselected(this.replicasResultados)
            ? false
            : true;
        },
        error: (error) => { },
      });
  }

  getPreviousSelected(
    muestreos: Array<ReplicasResultadosReglaVal>,
    muestreosSeleccionados: Array<ReplicasResultadosReglaVal>
  ) {
    muestreos.forEach((f) => {
      let muestreoSeleccionado = muestreosSeleccionados.find(
        (x) => f.resultadoMuestreoId === x.resultadoMuestreoId
      );

      if (muestreoSeleccionado != undefined) {
        f.selected = true;
      }
    });
  }

  cargarArchivo(event: any) { }
  enviarCorreo() { }
  onFilterIconClick(column: Column) { }
  sort(column: string, type: string) { }
  onDeleteFilterClick(columName: string) { }
  filtrar(columna: Column, isFiltroEspecial: boolean) { }
  onSelectClick(muestreo: any) { }

  

}
