export enum estatusMuestreo {  
  NoEnviado = 1,
  Enviado = 2,
  EnviadoConExtensionFecha = 3,
  Validado = 4,
  AprobacionFinal = 5,
  Eliminado = 6,
  EvidenciasCargadas = 7,
  AprobacionResultado = 8,
  DatoDudosoParaReplica = 9,
  DatoDudosoParaReplica_EnviadoLaboratorio = 10,
  EnviadoResultadosAprobados = 11,
  EnviadoParaReplica = 12,
  ReplicaConDiferenteDatoParaRevision = 13,
  RespuestaReplica = 14,
  RespuestaReplica_EnviadoLNR = 15,
  RespuestaReplica_ReglasValidacion_EnviadoPenalizacion = 16,
  RespuestaReplica_RespuestaLNR = 17,
  RespuestaReplica_RespuestaLNR_EnviadoPenalizacion = 18,
  RespuestaReplica_RespuestaLNR_EnviadoResultadosAprobados = 19,
  RespuestaReplica_RevisionOC_DL = 20,
  RespuestaReplica_RevisionSECAIA = 21,
  RespuestaReplica_ReglasValidacion = 22,
  ReplicaConDiferenteDato = 23,
  PendienteDeEnvioAprobacionFinal = 24,
  Cargado = 25,
  OriginalesAprobados = 26,
  ValidadoPorReglas = 27,
  SeleccionadoParaValidar = 28,

}
